module.exports = {
  apps: [
    {
      name: 'delala-api',
      script: 'src/server.js',
      instances: 'max',
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'development',
        PORT: 5000,
        ENABLE_TELEGRAM_POLLING: 'false',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5000,
        ENABLE_TELEGRAM_POLLING: 'false',
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'delala-bot',
      script: 'src/bot-worker.js',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'development',
        ENABLE_TELEGRAM_POLLING: 'true',
      },
      env_production: {
        NODE_ENV: 'production',
        ENABLE_TELEGRAM_POLLING: 'true',
      },
      error_file: './logs/pm2-bot-error.log',
      out_file: './logs/pm2-bot-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
