name: delala
description: Ethiopian House Rental Marketplace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  intl: ^0.20.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  google_maps_flutter: ^2.10.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
